// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj6kSispLfw9PGxrxl3AsvkAKuU01sGSw',
    appId: '1:59806118412:web:6fab7a31591b3f26dab429',
    messagingSenderId: '59806118412',
    projectId: 'chatapp-4b05a',
    authDomain: 'chatapp-4b05a.firebaseapp.com',
    storageBucket: 'chatapp-4b05a.appspot.com',
    measurementId: 'G-RTFQJ7EE39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkqGSgXRHwYpS2cB68VRP8blt6ctqC1GM',
    appId: '1:59806118412:android:8fd93b319900b5aedab429',
    messagingSenderId: '59806118412',
    projectId: 'chatapp-4b05a',
    storageBucket: 'chatapp-4b05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-7cCJ2Gc6giYjNQHjdJV9gLswzEvlqM',
    appId: '1:59806118412:ios:3c0453b591686104dab429',
    messagingSenderId: '59806118412',
    projectId: 'chatapp-4b05a',
    storageBucket: 'chatapp-4b05a.appspot.com',
    iosBundleId: 'com.chatapplicationusingflutterandfirebase.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5-7cCJ2Gc6giYjNQHjdJV9gLswzEvlqM',
    appId: '1:59806118412:ios:46253a873b8dbb89dab429',
    messagingSenderId: '59806118412',
    projectId: 'chatapp-4b05a',
    storageBucket: 'chatapp-4b05a.appspot.com',
    iosBundleId: 'com.chatapplicationusingflutterandfirebase.chatApp.RunnerTests',
  );
}
